index/urls.py
# coding=utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^/$',views.index,name='indexPage2'),
    url(r'^index/$', views.index, name='indexPage'),
    url(r'^aboutus/$', views.aboutus, name='aboutus'),
    url(r'^callus/$', views.callus, name='callus'),
    url(r'^joinus/$', views.joinus, name='joinus'),
    url(r'^loginOut/$', views.loginOut, name='loginOut'),
    url(r'^choujiang/$', views.choujiang, name='choujiang'),
    url(r'^voice_search/$', views.voice_search, name='voice_search'),
    ]

registerLogin/urls.py
from django.conf.urls import include, url
from . import views
from . import viewsUtils

urlpatterns = [
    # url(r'^$',views.index,name='index'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.login,name='login'),
    url(r'^regcheck/$',views.regcheck,name='regcheck'),
    url(r'^changekw/$',views.changekw,name='changekw'),
    url(r'^verifycode/$',viewsUtils.verifycode,name='verifycode'),
    url(r'^verify/$',views.verify,name='verify'),
]

shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from index import viewSearch
from django.conf import settings
from django.conf.urls.static import static
from haystack.views import SearchView
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    # url(r'^search/', include('haystack.urls')),
    url(r'^', include('registerLogin.urls', namespace='registerLogin')),
    url(r'^', include('usercenter.urls', namespace='usercenter')),
    url(r'^', include('goodslist.urls', namespace='goodslist')),
    url(r'^', include('index.urls', namespace='index')),
    url(r'^', include('detail.urls', namespace='detail')),
    url(r'^', include('cart.urls', namespace='cart')),
    url(r'^search/', viewSearch.MySearchView.as_view(), name='search_view'),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
]
# if settings.DEBUG:
#     urlpatterns = urlpatterns + static(
#     settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usercenter/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^user_center_info/$',views.user_center_info,name='user_center_info'),
    url(r'^user_center_order/$',views.user_center_order,name='user_center_order'),
    url(r'^user_center_site/$',views.user_center_site,name='user_center_site'),
    url(r'^areal/$',views.areal,name='areal'),
    url(r'^areal([0-9]+)/$',views.areal2,name='areal2'),
    url(r'^pay/$',views.pay,name='pay'),
]

cart/views.py
#coding=utf-8
from django.shortcuts import render,redirect
from django.core.urlresolvers import reverse
from django.http import *
from models import *
from django.db.models import *
from datetime import datetime
import time
from usercenter import der
@der.login_yz
@der.login_name
def cart(request,dic):
    '''
    从数据库读取购物信息
    '''
    cartlist = dic['user'].cart_set.all().filter(isDelete=False)
    car_good_list=[]
    for car in cartlist:
        car_good_list.append({'cart':car,'good':Goods.objects.get(id=int(car.goodsName))})
    dic=dict(dic,**{'lis':car_good_list})

    return render(request,"freshFruit/cart.html",dic)

@der.login_yz
def deleteHander(request):
    '''
    购物车删除操作，逻辑删除
    '''
    cartId=request.POST.get('cartId',None)
    print cartId
    if cartId:
        cart=Cart.objects.get(id=int(cartId))
        cart.isDelete=True
        cart.save()
        return JsonResponse({'response':'1'})
        

@der.login_yz
@der.login_name     
def place_order(request,dic):
    '''
    订单信息，取出购物车信息，或者立即购买的信息
    '''
    cartId=[]
    if request.method == 'GET':
        count=request.GET.get('count',None)
        goodId=request.GET.get('id',None)
        goodId=[goodId]
    elif request.method == 'POST':
        count=request.POST.getlist('count',None)
        cartId=request.POST.getlist('id',None)
        goodId=[]
        j=0
        for i in cartId:
            cart=Cart.objects.get(id=int(i))
            goodId.append(cart.goodsName)
            if int(count[j]) != cart.buyCount:
                cart.buyCount=int(count[j])
                cart.save()
            j += 1
    else:
        pass

    orderlist=[]
    freight = 10
    sumprice=0
    for i in range(len(goodId)):
        goods = Goods.objects.get(id=int(goodId[i]))
        orderdic={'goods':goods,'count':i+1,'sumtotal':goods.goodsPrice*int(count[i]),'goodscount':count[i]}
        if len(cartId)>0:
            orderdic['cartId']=cartId[i]
        orderlist.append(orderdic)
        sumprice += goods.goodsPrice*int(count[i])
    # area = AddrInfo.objects.filter(aUser_id=user.id).get(aDefaultAddr=True)
    AddrList=dic['user'].addrinfo_set.all()

    dic=dict(dic,**{
        'AddrList':AddrList,
        'orderlist':orderlist,
        'allprice':sumprice+freight,
        'freight':freight,
        'goodsamount':len(goodId),
        'alltotal': sumprice,
        'cartId':cartId,
    })
    return render(request,"freshFruit/place_order.html",dic)

@der.login_yz
@der.login_name
def place_hander(request,dic):
    '''
    订单处理，提交订单后删除购物车信息，生成订单，转向用户订单页
    '''
    addr= request.POST.get('addr')
    goodscount=request.POST.get('goodscount')
    goodsId= request.POST.get('goodsId')  #如果是立即购买的获取物品id
    cartIdList= request.POST.getlist('cartId') #如果是购物车结算的的获取购物车id
    orders=Orders()
    print addr
    orders.orderTime=datetime.now()
    orders.orderNumber=str(int(time.time()))
    orders.userOrder_id=dic['user'].id
    orders.addr=int(addr)
    orders.save()
    if cartIdList[0]:
        for i in cartIdList:
            cart=Cart.objects.get(id=int(i))
            goods=Goods.objects.get(id=int(cart.goodsName))
            OrderDetail=orders.orderdetail_set.create(goodsName=goods.goodsName,goodsPrice=goods.goodsPrice,buyCount=cart.buyCount,good_id_id=goods.id)
            OrderDetail.save()
            cart.isDelete=True
            cart.save()
    else:
        goods=Goods.objects.get(id=int(goodsId))
        orders.orderdetail_set.create(goodsName=goods.goodsName,goodsPrice=goods.goodsPrice,buyCount=int(goodscount),good_id_id=goods.id)
    return HttpResponseRedirect(reverse('usercenter:user_center_order'))

detail/views.py
# coding=utf-8
from django.shortcuts import render
from django.http import *
from models import *
from datetime import datetime
from usercenter import der
from django.core.urlresolvers import reverse


@der.login_name
def detail(request,dic):
    '''
    商品详情页呈现
    '''
    goodsId=request.GET.get('goodsId')
    if goodsId:
        good = Goods.objects.get(pk=goodsId)
    newgoodslist=good.goodSort.goods_set.all().order_by("-gPubdate")[0:2]

    GoodsComment=good.goodscomment_set.all().order_by("-commentDate")[0:2]
    if dic['user']:
        flag=False
        rece= dic['user'].recentsee_set.all().order_by('-id')[0:5]
        for i in rece:
            if i.goodsName==goodsId:
                flag=True
        if not flag:
            rec=RecentSee()
            rec.goodsName=goodsId
            rec.user_id=dic['user'].id
            rec.save()

    SortsMsg=GoodSort.objects.all() 
    dic2 ={
    'SortsMsg':SortsMsg,
    'goodSort':good.goodSort,
    'good':good,
    'newgoodslist':newgoodslist,
    'GoodsComment':GoodsComment,
    }
    dic=dict(dic, **dic2)
    return render(request,'freshFruit/detail.html',dic)

@der.login_yz
def comment(request,gid):
    '''
    商品评论
    '''
    comment=request.POST.get('comment',None)
    if comment and gid:
        goodc=GoodsComment()
        goodc.userName=request.session['name']
        goodc.commentDate=datetime.now()
        goodc.comment=comment
        goodc.goods_id=int(gid)
        goodc.save()
    
        return HttpResponseRedirect('/detail/?goodsId='+gid)
@der.login_yz
def addcart(request):
    '''
    加入购物车操作,写入数据库
    '''
    goodsID=request.POST.get('goodsName',None)
    buyCount=request.POST.get('buyCount',None)
    if goodsID and buyCount:
        name=request.session['name']
        user=UserInfo.objects.get(uName=name)
        cart=Cart()
        cart.goodsName=goodsID  #goodsName存储商品id 字符串类型，待修改
        cart.buyCount=int(buyCount)
        cart.userCart_id=user.pk
        cart.save()
        number=user.cart_set.filter(isDelete=False).count()
        return JsonResponse({'number':number})




                
            
            

templates/freshFruit/aboutus.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>关于我们</title>
</head>
<body topmargin="0">
	<table width="800" height="800" border="0" cellpadding="0" cellspacing="0" align="center">
		<tr>
			<td width="260" bgcolor="#f2f2f2" valign="top">
				<table width="230" border="0" cellpadding="0" cellspacing="0">
					<tr>
						<td height="100"></td>
					</tr>
					<tr>
						<td align="right">
							<a href="{% url 'index:indexPage' %}"><img src="{% static 'images/logo.png' %}"></a>
						</td>
					</tr>
					<tr><td align="right"><font color="#5f5f5f" size='3' face="Microsoft Yahei"><b>call us:</b></font></td></tr>
					<tr><td align="right" height="30"><font color="#5f5f5f" size='3' face="Microsoft Yahei">654388888</font></td></tr>
					<tr><td align="right" height="30"><font color="#5f5f5f" size='3' face="Microsoft Yahei">daydayfresh@163.com</font></td></tr>
				</table>					
			</td>
			<td width="30"></td>
			<td width="480" valign="top">
				<table width="440" border="0" cellpadding="0" cellspacing="0">
					<tr><td height="45"></td></tr>
					<tr>
						<tr><td align="right"><font color="#5f5f5f" size='4' face="Microsoft Yahei"><b>北京天天生鲜科技有限公司</b></font></td></tr>
					</tr>
				</table>
				<br />
				<hr width="100%" style="margin-top:-5px;border:3px solid #47aa34;"/>

				<br />
					<table width="440" border="0" cellpadding="5" cellspacing="0">
						<tr>
							<font size="3" color="#5f5f5f" face="Microsoft Yahei">
							    &nbsp;&nbsp;  北京天天生鲜科技有限公司是一家在线销售时令水果，海鲜水产，猪牛羊肉，禽类蛋
							品，禽类蛋品，新鲜蔬菜，速冻食品的的互联网+企业。公司借助互联网平台，做到了线上与线下相结合的发展战略。
							</font>									
						</tr>
					</table>
					<br />
					<table cellspacing="0" cellpadding="5">
						<tr>
							<td><font size="4" color="#5f5f5f" face="Microsoft Yahei"><b>公司大事记</b></font></td>
						</tr>
						<tr>
							<td><font size="3" color="#5f5f5f" face="Microsoft Yahei"><b>2008.09-2011.06</b>&nbsp;公司挂牌成立</font></td>
						</tr>
						<tr>
							<td><font size="3" color="#5f5f5f" face="Microsoft Yahei"><b>2011.06-2012.09</b>&nbsp;公司推出互联网平台</font></td>
						</tr>
					</table>
					<br />
					<table cellspacing="0" cellpadding="5">
						<tr>
							<td><font size="4" color="#5f5f5f" face="Microsoft Yahei"><b>所获荣誉</b></font></td>
						</tr>
						<tr>
							<td><font size="3" color="#5f5f5f" face="Microsoft Yahei"><b>2009年：</b>荣获"健康肉类"证书</font></td>
						</tr>
						<tr>
							<td><font size="3" color="#5f5f5f" face="Microsoft Yahei"><b>2009年：</b>荣获"可靠放心产品"证书</font></td>
						</tr>
					</table>
			</td>
			<td width="30"></td>
		</tr>		
	</table>
</body>
</html>

templates/freshFruit/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{%block title%}{%endblock%} </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
{%block top%}
<div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                <div class="login_info fl">
                    欢迎您：<em>{{user.uName}}</em>
                </div>
                <div class="login_btn fl">
                    <a href="{% url 'registerLogin:login'%}">登录</a>
                    <span>|</span>
                    <a href="{% url 'registerLogin:register'%}">注册</a>
                </div>

                
                <div class="login_btn fl" id='login_btn_out'>
                    <span>|</span>
                    <a href="/loginOut/">退出</a>
                </div>

                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'usercenter:user_center_info'%}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:cart'%}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'usercenter:user_center_order'%}">我的订单</a>
                </div>
            </div>
        </div>      
    </div>
    <script src="http://apps.bdimg.com/libs/jquery/1.9.1/jquery.min.js"></script> 
    {% comment%}<script type="text/javascript" src="{% static 'jquery-1.12.4.js' %}"></script>
    {% endcomment %}
        <script type="text/javascript">
            $(function(){
                if ($('.login_info em').html() != ''){
                    $('.login_info').show();
                    $('.login_btn').hide();
                    $('#login_btn_out').show();
                }
                else
                {
                    $('.login_info').hide();
                    $('.login_btn').show();
                    $('#login_btn_out').hide();
                }
            })  
        </script>

{%endblock%}

{%block menu%}{%endblock%}

{%block content%}{%endblock%}

{%block class%}<div class="footer">{%endblock%}
        <div class="foot_link">
            <a href="{% url 'index:aboutus' %}">关于我们</a>
            <span>|</span>
            <a href="{% url 'index:callus' %}">联系我们</a>
            <span>|</span>
            <a href="{% url 'index:joinus' %}">招聘人才</a>
            <span>|</span>
            <a href="{% url 'index:indexPage' %}">友情链接</a>      
        </div>

        <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
        <p>电话：010-6543888    京ICP备654388888号</p>
    </div>
</body>
</html>

templates/freshFruit/base_index.html
{%extends 'freshFruit/base.html'%}
{% load static from staticfiles %}
{%block title%}天天生鲜-用户中心{%endblock%}

{%block menu%}
<div class="search_bar clearfix">
        <a href="{% url 'index:indexPage' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="search_con fl" style='position: relative'>
            <form action="/search/" target="_blank">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
                <!--<input name="" type="button"   style=" width:38px; height:38px;  border:0;position:absolute; left:620px; background:url({% static 'images/logo.png' %}) no-repeat right top" /> -->
                <a href="{%url 'index:voice_search'%}"><img src="{% static 'images/logo.png' %}" style=" width:38px; height:38px; border:0; position:absolute; left:620px;" /></a>
            </form>
        </div>
        <div class="guest_cart fr">
                <i id="end"></i>

            <a href="{% url 'cart:cart'%}" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{number}}</div>
        </div>
    </div>

    {%block navlist%}
    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>   
                <span></span>           
                <ul class="subnav">


            {% for temp in SortsMsg %}
            <li><a href="{% url 'goodslist:list'%}?order=id&&sort={{temp.id}}" class="{{temp.sortClass}}">{{temp.sortName}}</a></li>
            {% endfor temp %}

                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>
    {%endblock%}
{%endblock%}

templates/freshFruit/base_user.html
{%extends 'freshFruit/base.html'%}
{% load static from staticfiles %}
{%block title%}天天生鲜-用户中心{%endblock%}

{%block menu%}
<div class="search_bar clearfix">
        <a href="{% url 'index:indexPage' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{%block option%}{%endblock%}</div>
        <div class="search_con fr">
            <form action="/search/" target="_blank">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
                <input type="submit" class="input_btn fr" name="" value="语音搜索">
            </form>
        </div>      
    </div>
    {%block user_message%}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                {%block tab_info%}<li><a href="{% url 'usercenter:user_center_info'%}" >· 个人信息</a></li>
                {%endblock %}
                {%block tab_order%}
                <li><a href="{% url 'usercenter:user_center_order'%}" >· 全部订单</a></li>
                {%endblock %}
                {%block tab_site%}
                <li><a href="{% url 'usercenter:user_center_site'%}" >· 收货地址</a></li>
                {%endblock %}
            </ul>
        </div>
    {%endblock %}


{%endblock%}

templates/freshFruit/index.html
{%extends 'freshFruit/base_index.html'%}

{% load static from staticfiles %}

{%block title%}天天生鲜首页{%endblock%}


{%block content%}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/slide.js"></script>
    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="{%url 'index:choujiang'%}">抽奖</a></li>
            </ul>
        </div>
    </div>
    <div class="center_con clearfix">
        <ul class="subnav fl">
            {% for temp in message %}
            <li><a href="#model{{temp.sort.id}}" class="{{temp.sort.sortClass}}">{{temp.sort.sortName}}</a></li>
            {% endfor temp %}
        </ul>

        <div class="slide fl">
            <ul class="slide_pics">
                <li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
                <li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
                <li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
                <li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>
        <div class="adv fl" >
            <a href="#" style="width: 240px;height: 135px;"><img src="/static/images/adv01.jpg"></a>
            <a href="#" style="width: 240px;height: 135px;"><img src="/static/images/adv02.jpg"></a>
        </div>
    </div>



{%for i in message %}
<div class="list_model">
        <div class="list_title clearfix">
        
            <h3 class="fl" id="model{{i.sort.id}}">{{i.sort.sortName}}</h3>
            <div class="subtitle fl">
                <span>|</span>
                
                    {%for ogood in i.goodOtherList%}
                                <a href="/detail/?goodsId={{ogood.id}}">{{ogood.goodsName}}</a>
                    {%endfor%}
                
            </div>
            <a href="{% url 'goodslist:list'%}?sort={{i.sort.id}}" class="goods_more fr" id="fruit_more">查看更多 ></a>
        </div>
                <div class="goods_con clearfix">
            <div class="goods_banner fl"><img src="/static/uploads/{{i.sort.sortPic}}"></div>
            <ul class="goods_list fl">
                    {% for good in i.goodMsgList %}
                <li>
                    <h4><a href="/detail/?goodsId={{good.id}}">{{ good.goodsName }}</a></h4>
                    <a href="/detail/?goodsId={{good.id}}"><img src="/static/uploads/{{good.imgPath}}"></a>
                    <div class="prize">¥ {{ good.goodsPrice }}</div>
                </li>
                    {% endfor %}
    
            </ul>
        </div>
{%endfor%}


{%endblock%}

{% block navlist %}
{% endblock %}

templates/freshFruit/login.html
{%extends 'freshFruit/base.html'%}
{% load static from staticfiles %}

{%block title%}天天生鲜-登录{%endblock%}
{%block top%}{%endblock%}


{%block content%}
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script type="text/javascript">
            $(function() {
            $('#verifychangecode').css('cursor','pointer').click(function(){
                $('#verifycode').attr('src','/verifycode/?'+Math.random())
            });
        });
</script>

<div class="login_top clearfix">
        <a href="{% url 'index:indexPage' %}" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>   
    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">日夜兼程 · 急速送达</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登录</h1>
                    <a href="{% url 'registerLogin:register'%}">立即注册</a>
                </div>
                <div class="form_input">
                    <form action="{% url 'registerLogin:login'%}" method="post">
                        <input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{user.uName}}">
                        <div class="user_error">{{error.name}}</div>
                        <input type="password" name="pwd" class="pass_input" placeholder="请输入密码"  >
                        <div class="pwd_error">{{error.password}}</div>
                        <div class='yzm_check'>
                                <!-- 验证码 -->                                                         
                                <input type="text" class="yzm_input" name="ucode">
                                <img id='verifycode' class='verifycode' src="/verifycode/" name='vecode' alt="CheckCode">
                                <span id="verifychangecode">看不清楚，换一个</span>
                        </div>

                        <div class="more_input clearfix">
                            <input type="checkbox" name="check">
                            <label>记住用户名</label>
                            <a href="{% url 'registerLogin:changekw' %}">忘记密码</a>
                        </div>
                        <input type="submit" name="" value="登录" class="input_submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
        if ($('.user_error').html() != '') {$('.user_error').show()};
        if ($('.pwd_error').html() != ''){$('.pwd_error').show()};
    </script>
{%endblock%}
{%block class%}<div class="footer no-mp">{%endblock%}

templates/freshFruit/register.html
{%extends 'freshFruit/base.html'%}
{% load static %}

{%block title%}天天生鲜-注册{%endblock%}
{%block top%}
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/register.js'%}"></script>
{%endblock%}


{%block content%}
<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo" href="{% url 'index:indexPage' %}"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'registerLogin:login'%}">登录</a>
			</div>
			<div class="reg_form clearfix" id='reg_form'>
				<form method="post" action="{% url 'registerLogin:register'%}">
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{%endblock%}

templates/freshFruit/verify.html
<!DOCTYPE html>
<html>
<head>
    <title>验证码</title>
</head>
<body>
        <img id='verifycode' src="/verifycode/" alt="CheckCode">
</body>
</html>